title: Alan Turing challenges
description: Site com a lista de exercicios para os campeonatos de programação
github_username:  turing-challenges

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
